INSERT INTO BOOK
SELECT I, 1,
	MD5(RANDOM()::text),
	FLOOR(RANDOM() * 1000)::int
FROM GENERATE_SERIES(16, 10016) S(I);


DROP INDEX IF EXISTS BOOK_YEAR_TITLE_IDX;


CREATE INDEX IF NOT EXISTS BOOK_YEAR_TITLE_IDX ON BOOK(YEAR, TITLE);

EXPLAIN ANALYZE
SELECT *
FROM BOOK AS B
WHERE B.TITLE like 'a10'
	AND B.YEAR = 1000;


INSERT INTO AUTHOR
SELECT I,
	MD5(RANDOM()::text),
	MD5(RANDOM()::text),
	MD5(RANDOM()::text),
	MD5(RANDOM()::text),
	MD5(RANDOM()::text)
FROM GENERATE_SERIES(16, 10016) S(I);


DROP INDEX IF EXISTS AUTHOR_NAME_DIRTHDATE_IDX;


CREATE INDEX IF NOT EXISTS AUTHOR_NAME_BIRTHDATE_IDX ON AUTHOR(NAME, BIRTHDATE);

EXPLAIN ANALYZE
SELECT *
FROM AUTHOR AS A
WHERE A.NAME like 'n1'
	AND A.BIRTHDATE LIKE 'b1';