DROP VIEW IF EXISTS BOOK_COUNT_STAT_VIEW;


CREATE VIEW BOOK_COUNT_STAT_VIEW AS
SELECT B.TITLE AS BOOK_TITLE,
	P.NAME AS PUBLISHER_NAME,
	SUM(SCB.COUNT) AS COUNT_BOOK_TAKEN,
	SUM(WB.COUNT) AS COUNT_BOOK_ON_WAREHOUSES
FROM BOOK AS B
JOIN PUBLISHER AS P ON P.PUBLISHER_ID = B.PUBLISHER_ID
JOIN SHOPPING_CART_BOOK AS SCB ON SCB.BOOK_ID = B.BOOK_ID
JOIN WAREHOUSE_BOOK AS WB ON WB.BOOK_ID = B.BOOK_ID
GROUP BY B.BOOK_ID,
	P.PUBLISHER_ID
ORDER BY COUNT_BOOK_TAKEN